version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    links:
      - db

  datos:
    container_name: datos
    build: ./Datos_DB
    restart: always
    depends_on:
      - db
    links:
      - db

  api:
    container_name: api
    build: ./API
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
  front:
    container_name: front
    build: ./Front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api

